SHELL=/bin/bash
general:
	tigernotes doc {Information,SummaryStats,QuasiPoissonModel,MultiTissueAnalysis}.notes -o Notes --footnote --font_size 12 -a "Gao Wang" -t "GTEx eQTL analysis notes"
sumstatsdb:
	tigernotes doc SumstatsDB.notes -o SumstatsDB.pdf --footnote --font_size 12 -a "Gao Wang" -t "GTEx summary statistics database"
