"""
eqtlbma pipeline

This pipeline analyzes eQTL data via eqtlbma program, under
various BMA models.
"""
__author__ = "Gao Wang"
# use a modified version of shell.py from snakemake
from shell import shell

# Global settings
configfile: "config.yaml"

if config["IsCluster"] == "F":
    shell.executable("/bin/bash")
    shell.prefix(config["ConfigBash"])
else:
    shell.prefix('''
    echo """#!/bin/bash
    {0}
    '''.format(config["ConfigBash"]))
    shell.suffix('''""" {1} {0}'''.format(config["ConfigCluster"].replace("LOGDIR", config["LogDir"]),
                                          "|" if config["ConfigCluster"] else ''))
    shell.echo(True)

# Rules
include: "../../rules/eqtlbma-bf.rules"

rule clean:
  shell: "rm -rf {config[TmpDir]}/*"
