"""
Single tissue eQTL analysis
"""
__author__ = "Gao Wang"

# Global settings
configfile: "../config.yaml"
shell.executable("/bin/bash")
shell.prefix(config["ConfigBash"])
TISSUES, = glob_wildcards(config["SSData"] + "/{tissue}.cis.eqtl.gz")

# Rules
include: "../../rules/sumstat-to-h5.rules"
include: "../../rules/file-processing.rules"
include: "../../rules/matrix-eqtl.rules"
include: "../../rules/eqtlbma-batch.rules"

rule clean:
  shell: "rm -rf {config[TmpDir]}/*"
